name: USOM API to ProxySG Sync

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Yükle
      run: pip install requests

    - name: API'den Veri Çek ve Formatla
      run: python update_list.py

    - name: GitHub Pages Altyapısını Hazırla
      uses: actions/configure-pages@v4

    - name: Dosyaları Paketle
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: İnternette Yayınla (Deploy)
      id: deployment
      uses: actions/deploy-pages@v4
